import joblib
import m2cgen as m2c
import os

def export():
    # 1. Load the model
    if not os.path.exists("static_ml_model.pkl"):
        print("Error: static_ml_model.pkl not found!")
        return
        
    model = joblib.load("static_ml_model.pkl")
    classes = joblib.load("static_ml_classes.pkl")
    n_features = model.n_features_in_
    print(f"Exporting model with {len(classes)} classes and {n_features} features...")
    
    # 2. Generate C++ code
    code = m2c.export_to_c(model)
    
    # 3. Wrap in our HPP format
    hpp_content = """#pragma once
#include <vector>
#include <string>
#include <algorithm>

namespace StaticModel {
// Auto-generated by m2cgen
#include <string.h>
"""
    # Insert the m2cgen generated function
    hpp_content += code
    hpp_content += "\n} // namespace StaticModel\n"
    
    # 4. Add the Classifier Class
    hpp_content += """
class StaticSignClassifier {
public:
    static std::vector<std::string> get_classes() {
        return {""" 
    hpp_content += ", ".join([f'"{c}"' for c in classes])
    hpp_content += """};
    }

    static std::string predict(const std::vector<float>& features) {
        double output[""" + str(len(classes)) + """];
        double input_arr[""" + str(n_features) + """];
        
        for(size_t i=0; i<features.size() && i<""" + str(n_features) + """; ++i) {
            input_arr[i] = features[i];
        }
        
        StaticModel::score(input_arr, output);
        
        int max_idx = 0;
        double max_val = output[0];
        for(int i=1; i<""" + str(len(classes)) + """; ++i) {
            if(output[i] > max_val) {
                max_val = output[i];
                max_idx = i;
            }
        }
        
        return get_classes()[max_idx];
    }
};
"""

    with open("StaticSignClassifier.hpp", "w") as f:
        f.write(hpp_content)
        
    print("Done! StaticSignClassifier.hpp updated.")

if __name__ == "__main__":
    export()
