import joblib
import m2cgen as m2c
import os

print("Loading trained dynamic model...")
clf = joblib.load("dynamic_ml_model.pkl")
classes = joblib.load("dynamic_ml_classes.pkl")

print("Transpiling model to pure C++...")
cpp_code = m2c.export_to_c(clf)

# Rename the 'score' function to avoid clash with static model
cpp_code = cpp_code.replace("void score(", "void dynamic_score(")

cpp_wrapper = f"""#pragma once
#include <vector>
#include <string>
#include <algorithm>

namespace DynamicModel {{
// Auto-generated by m2cgen
{cpp_code}
}} // namespace DynamicModel

class DynamicSignClassifier {{
public:
    static std::vector<std::string> get_classes() {{
        return {{
            "{'","'.join(classes)}"
        }};
    }}

    static std::vector<double> predict_proba(const std::vector<float>& features) {{
        double output[{len(classes)}];
        double input_arr[{len(clf.feature_importances_)}];
        
        for(size_t i=0; i<features.size(); ++i) {{
            input_arr[i] = features[i];
        }}
        
        DynamicModel::dynamic_score(input_arr, output);
        
        std::vector<double> probs(output, output + {len(classes)});
        return probs;
    }}
}};
"""

with open("DynamicSignClassifier.hpp", "w") as f:
    f.write(cpp_wrapper)

print("Success! Wrote model to 'DynamicSignClassifier.hpp'")
