import joblib
import m2cgen as m2c
import os

print("Loading trained model...")
clf = joblib.load("static_ml_model.pkl")
classes = joblib.load("static_ml_classes.pkl")

print("Transpiling model to pure C++ (This may take a minute for a Random Forest)...")
# m2cgen converts the entire scikit-learn model into a raw C++ function!
# We set function_name to "predict_static_sign"
cpp_code = m2c.export_to_c(clf)

# m2cgen outputs standard C code. We'll wrap it nicely.
cpp_wrapper = f"""#pragma once
#include <vector>
#include <string>
#include <algorithm>

// Auto-generated by m2cgen
{cpp_code}

class StaticSignClassifier {{
public:
    static std::string predict(const std::vector<float>& features) {{
        // The m2cgen code outputs a double array of probabilities for each class
        double output[{len(classes)}];
        double input_arr[{len(clf.feature_importances_)}];
        
        for(size_t i=0; i<features.size(); ++i) {{
            input_arr[i] = features[i];
        }}
        
        score(input_arr, output);
        
        // Find highest probability
        int max_idx = 0;
        for (int i = 1; i < {len(classes)}; ++i) {{
            if (output[i] > output[max_idx]) {{
                max_idx = i;
            }}
        }}
        
        // Map index back to string
        std::vector<std::string> classes = {{
            "{'","'.join(classes)}"
        }};
        
        return classes[max_idx];
    }}
}};
"""

with open("StaticSignClassifier.hpp", "w") as f:
    f.write(cpp_wrapper)

print("Success! Wrote model to 'StaticSignClassifier.hpp'")
